const errors = {
  category_get_validation_error: "Category get validation error",
  category_post_validation_error: "Category post validation error",
  category_patch_validation_error: "Category patch validation error",
  category_delete_validation_error: "Category delete validation error",
  category_get_error: "Category get error",
  category_post_error: "Category post error",
  category_patch_error: "Category patch error",
  category_delete_error: "Category delete error",
  category_not_found: "Category not found",
  category_already_exists: "Category already exists",
  category_invalid_id: "Category invalid id",
  category_invalid_name: "Category invalid name",
  category_invalid_image: "Category invalid image",
  category_invalid_description: "Category invalid description",
  category_invalid_taxable: "Category invalid taxable",
  category_invalid_tax: "Category invalid tax",
  category_invalid_created_at: "Category invalid created_at",
  category_invalid_updated_at: "Category invalid updated_at",
  category_invalid_deleted_at: "Category invalid deleted_at",
  category_invalid_deleted: "Category invalid deleted",
  category_invalid: "Category invalid",
  category_invalid_category: "Category invalid category",
  category_invalid_category_id: "Category",

  subcategory_get_validation_error: "Subcategory get validation error",
  subcategory_post_validation_error: "Subcategory post validation error",
  subcategory_patch_validation_error: "Subcategory patch validation error",
  subcategory_delete_validation_error: "Subcategory delete validation error",
  subcategory_get_error: "Subcategory get error",
  subcategory_post_error: "Subcategory post error",
  subcategory_patch_error: "Subcategory patch error",
  subcategory_delete_error: "Subcategory delete error",
  subcategory_not_found: "Subcategory not found",
  subcategory_already_exists: "Subcategory already exists",
  subcategory_invalid_id: "Subcategory invalid id",
  subcategory_invalid_name: "Subcategory invalid name",
  subcategory_invalid_image: "Subcategory invalid image",
  subcategory_invalid_description: "Subcategory invalid description",
  subcategory_invalid_taxable: "Subcategory invalid taxable",
  subcategory_invalid_tax: "Subcategory invalid tax",
  subcategory_invalid_created_at: "Subcategory invalid created_at",
  subcategory_invalid_updated_at: "Subcategory invalid updated_at",
  subcategory_invalid_deleted_at: "Subcategory invalid deleted_at",
  subcategory_invalid_deleted: "Subcategory invalid deleted",
  subcategory_invalid: "Subcategory invalid",
  subcategory_invalid_category: "Subcategory invalid category",
  subcategory_invalid_category_id: "Subcategory invalid category_id",
  subcategory_invalid_subcategory: "Subcategory invalid subcategory",
  subcategory_invalid_subcategory_id: "Subcategory invalid subcategory_id",
  subcategory_invalid_subcategory_name: "Subcategory invalid subcategory_name",
  subcategory_invalid_subcategory_image: "Subcategory invalid subcategory_image",
  subcategory_invalid_subcategory_description: "Subcategory invalid subcategory_description",
  subcategory_invalid_subcategory_taxable: "Subcategory invalid subcategory_taxable",
  subcategory_invalid_subcategory_tax: "Subcategory invalid subcategory_tax",
  subcategory_invalid_subcategory_created_at: "Subcategory invalid subcategory_created_at",
  subcategory_invalid_subcategory_updated_at: "Subcategory invalid subcategory_updated_at",
  subcategory_invalid_subcategory_deleted_at: "Subcategory invalid subcategory_deleted_at",
  subcategory_invalid_subcategory_deleted: "Subcategory invalid subcategory_deleted",
  subcategory_invalid_subcategory_category_id: "Subcategory invalid subcategory_category_id",
  subcategory_invalid_subcategory_category: "Subcategory invalid subcategory_category",
  subcategory_invalid_subcategory_subcategory: "Subcategory invalid subcategory_subcategory",
  subcategory_invalid_subcategory_subcategory_id: "Subcategory invalid subcategory_subcategory_id",
  subcategory_invalid_subcategory_subcategory_name: "Subcategory invalid subcategory_subcategory_name",
  subcategory_invalid_subcategory_subcategory_image: "Subcategory invalid subcategory_subcategory_image",
  subcategory_invalid_subcategory_subcategory_description:
    "Subcategory invalid subcategory_subcategory_description",
  subcategory_invalid_subcategory_subcategory_taxable: "Subcategory invalid subcategory_subcategory_taxable",
  subcategory_invalid_subcategory_subcategory_tax: "Subcategory invalid subcategory_subcategory_tax",
  subcategory_invalid_subcategory_subcategory_created_at:
    "Subcategory invalid subcategory_subcategory_created_at",
  subcategory_invalid_subcategory_subcategory_updated_at:
    "Subcategory invalid subcategory_subcategory_updated_at",
  subcategory_invalid_subcategory_subcategory_deleted_at:
    "Subcategory invalid subcategory_subcategory_deleted_at",
  subcategory_invalid_subcategory_subcategory_deleted: "Subcategory invalid subcategory_subcategory_deleted",
  subcategory_invalid_subcategory_subcategory_category_id:
    "Subcategory invalid subcategory_subcategory_category_id",
  subcategory_invalid_subcategory_subcategory_category:
    "Subcategory invalid subcategory_subcategory_category",
  subcategory_invalid_subcategory_subcategory_subcategory:
    "Subcategory invalid subcategory_subcategory_subcategory",
  subcategory_invalid_subcategory_subcategory_subcategory_id:
    "Subcategory invalid subcategory_subcategory_subcategory_id",
  subcategory_invalid_subcategory_subcategory_subcategory_name:
    "Subcategory invalid subcategory_subcategory_subcategory_name",

  item_get_validation_error: "Item get validation error",
  item_post_validation_error: "Item post validation error",
  item_patch_validation_error: "Item patch validation error",
  item_delete_validation_error: "Item delete validation error",
  item_get_error: "Item get error",
  item_post_error: "Item post error",
  item_patch_error: "Item patch error",
  item_delete_error: "Item delete error",
  item_not_found: "Item not found",
  item_already_exists: "Item already exists",
  item_invalid_id: "Item invalid id",
  item_invalid_name: "Item invalid name",
  item_invalid_image: "Item invalid image",
  item_invalid_description: "Item invalid description",
  item_invalid_taxable: "Item invalid taxable",
  item_invalid_tax: "Item invalid tax",
  item_invalid_base_amount: "Item invalid base_amount",
  item_invalid_discount: "Item invalid discount",
  item_invalid_total_amount: "Item invalid total_amount",
  item_invalid_created_at: "Item invalid created_at",
  item_invalid_updated_at: "Item invalid updated_at",
  item_invalid_deleted_at: "Item invalid deleted_at",
  item_invalid_deleted: "Item invalid deleted",
  item_invalid: "Item invalid",
  item_invalid_category_id: "Item invalid category_id",
  item_invalid_category: "Item invalid category",
  item_invalid_subcategory_id: "Item invalid subcategory_id",
  item_invalid_subcategory: "Item invalid subcategory",
  item_invalid_item: "Item invalid item",
  item_invalid_item_id: "Item invalid item_id",
  item_invalid_item_name: "Item invalid item_name",
  item_invalid_item_image: "Item invalid item_image",
  item_invalid_item_description: "Item invalid item_description",
  item_invalid_item_taxable: "Item invalid item_taxable",
  item_invalid_item_tax: "Item invalid item_tax",
  item_invalid_item_base_amount: "Item invalid item_base_amount",
  item_invalid_item_discount: "Item invalid item_discount",
  item_invalid_item_total_amount: "Item invalid item_total_amount",
  item_invalid_item_created_at: "Item invalid item_created_at",
  item_invalid_item_updated_at: "Item invalid item_updated_at",
}

export default errors
