version: '2'
services:
  node:
    build: ./
    restart: always
    container_name: menu-management
    volumes:
      - ./lib:/app/lib
      - ./migrations:/app/migrations
      - ./tests:/app/tests
    ports:
      - "4000:4000"
