version: '2'
services:
  mysqldb:
    image: mysql:8.0.20
    container_name: menu-management-sql
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
     - ./init.sql:/data/application/init.sql
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${mysql_host}
    depends_on:
      - mysqldb